//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Escyug.Converter.Models.RecipesServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RecipesServiceReference.RecipeServiceSoap")]
    public interface RecipeServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.Recipe[] RecipeRequest(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.Recipe[]> RecipeRequestAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeRequestRepeat", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.Recipe[] RecipeRequestRepeat(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeRequestRepeat", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.Recipe[]> RecipeRequestRepeatAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeResponse", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        void RecipeResponse(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo[] recipes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeResponse", ReplyAction="*")]
        System.Threading.Tasks.Task RecipeResponseAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo[] recipes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeFind", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.Recipe RecipeFind(string clientId, string seria, string number, System.DateTime saleDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeFind", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.Recipe> RecipeFindAsync(string clientId, string seria, string number, System.DateTime saleDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        string RecipeCheck(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RecipeCheckAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeEditCheck", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        string RecipeEditCheck(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeEditCheck", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RecipeEditCheckAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeDelay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        string RecipeDelay(string clientId, string seria, string number, System.DateTime incomeDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeDelay", ReplyAction="*")]
        System.Threading.Tasks.Task<string> RecipeDelayAsync(string clientId, string seria, string number, System.DateTime incomeDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeClientSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.RecipeClient RecipeClientSave(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeClientSave", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeClient> RecipeClientSaveAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient recipe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipesClientSave", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.RecipeClient[] RecipesClientSave(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient[] recipes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipesClientSave", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeClient[]> RecipesClientSaveAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient[] recipes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipesClient2Save", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.RecipeClient2Out[] RecipesClient2Save(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient2[] recipes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipesClient2Save", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeClient2Out[]> RecipesClient2SaveAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient2[] recipes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeReestrRequest", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.RecipeReestr[] RecipeReestrRequest(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipeReestrRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeReestr[]> RecipeReestrRequestAsync(string clientId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipesClientHashesExchange", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(Entity))]
        Escyug.Converter.Models.RecipesServiceReference.DocumentHash[] RecipesClientHashesExchange(string clientId, Escyug.Converter.Models.RecipesServiceReference.DocumentHash[] documentHashes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/RecipesClientHashesExchange", ReplyAction="*")]
        System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.DocumentHash[]> RecipesClientHashesExchangeAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.DocumentHash[] documentHashes);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Recipe : Entity {
        
        private string seriaField;
        
        private string numberField;
        
        private string fioField;
        
        private string unifyIdField;
        
        private string unifyNameField;
        
        private string unifyCodeField;
        
        private string tradeNameField;
        
        private string nonproprietaryNameField;
        
        private string dosageField;
        
        private string cureFormField;
        
        private string cureFormIdField;
        
        private decimal quantityField;
        
        private decimal quantityElementsField;
        
        private int packageSizeField;
        
        private int denominatorField;
        
        private decimal creditField;
        
        private string idLotGlobalField;
        
        private System.DateTime expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private bool allowRecipeReserveMultiSupplierField;
        
        private bool allowRecipeReserveMultiGoscontractField;
        
        private string invalidField;
        
        private RecipeReserveInfo[] recipeReserveInfosField;
        
        private MnnItem[] mnnItemsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Seria {
            get {
                return this.seriaField;
            }
            set {
                this.seriaField = value;
                this.RaisePropertyChanged("Seria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Fio {
            get {
                return this.fioField;
            }
            set {
                this.fioField = value;
                this.RaisePropertyChanged("Fio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string UnifyId {
            get {
                return this.unifyIdField;
            }
            set {
                this.unifyIdField = value;
                this.RaisePropertyChanged("UnifyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string UnifyName {
            get {
                return this.unifyNameField;
            }
            set {
                this.unifyNameField = value;
                this.RaisePropertyChanged("UnifyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string UnifyCode {
            get {
                return this.unifyCodeField;
            }
            set {
                this.unifyCodeField = value;
                this.RaisePropertyChanged("UnifyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string TradeName {
            get {
                return this.tradeNameField;
            }
            set {
                this.tradeNameField = value;
                this.RaisePropertyChanged("TradeName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NonproprietaryName {
            get {
                return this.nonproprietaryNameField;
            }
            set {
                this.nonproprietaryNameField = value;
                this.RaisePropertyChanged("NonproprietaryName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Dosage {
            get {
                return this.dosageField;
            }
            set {
                this.dosageField = value;
                this.RaisePropertyChanged("Dosage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string CureForm {
            get {
                return this.cureFormField;
            }
            set {
                this.cureFormField = value;
                this.RaisePropertyChanged("CureForm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string CureFormId {
            get {
                return this.cureFormIdField;
            }
            set {
                this.cureFormIdField = value;
                this.RaisePropertyChanged("CureFormId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public decimal QuantityElements {
            get {
                return this.quantityElementsField;
            }
            set {
                this.quantityElementsField = value;
                this.RaisePropertyChanged("QuantityElements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int PackageSize {
            get {
                return this.packageSizeField;
            }
            set {
                this.packageSizeField = value;
                this.RaisePropertyChanged("PackageSize");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int Denominator {
            get {
                return this.denominatorField;
            }
            set {
                this.denominatorField = value;
                this.RaisePropertyChanged("Denominator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public decimal Credit {
            get {
                return this.creditField;
            }
            set {
                this.creditField = value;
                this.RaisePropertyChanged("Credit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string IdLotGlobal {
            get {
                return this.idLotGlobalField;
            }
            set {
                this.idLotGlobalField = value;
                this.RaisePropertyChanged("IdLotGlobal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified {
            get {
                return this.expirationDateFieldSpecified;
            }
            set {
                this.expirationDateFieldSpecified = value;
                this.RaisePropertyChanged("ExpirationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool AllowRecipeReserveMultiSupplier {
            get {
                return this.allowRecipeReserveMultiSupplierField;
            }
            set {
                this.allowRecipeReserveMultiSupplierField = value;
                this.RaisePropertyChanged("AllowRecipeReserveMultiSupplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool AllowRecipeReserveMultiGoscontract {
            get {
                return this.allowRecipeReserveMultiGoscontractField;
            }
            set {
                this.allowRecipeReserveMultiGoscontractField = value;
                this.RaisePropertyChanged("AllowRecipeReserveMultiGoscontract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string Invalid {
            get {
                return this.invalidField;
            }
            set {
                this.invalidField = value;
                this.RaisePropertyChanged("Invalid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=21)]
        public RecipeReserveInfo[] RecipeReserveInfos {
            get {
                return this.recipeReserveInfosField;
            }
            set {
                this.recipeReserveInfosField = value;
                this.RaisePropertyChanged("RecipeReserveInfos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=22)]
        public MnnItem[] MnnItems {
            get {
                return this.mnnItemsField;
            }
            set {
                this.mnnItemsField = value;
                this.RaisePropertyChanged("MnnItems");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecipeReserveInfo : Entity {
        
        private string seriaField;
        
        private string numberField;
        
        private string programIdField;
        
        private string programNameField;
        
        private string contractIdField;
        
        private string contractNumberField;
        
        private string contractNameField;
        
        private string recipeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Seria {
            get {
                return this.seriaField;
            }
            set {
                this.seriaField = value;
                this.RaisePropertyChanged("Seria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ProgramId {
            get {
                return this.programIdField;
            }
            set {
                this.programIdField = value;
                this.RaisePropertyChanged("ProgramId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProgramName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
                this.RaisePropertyChanged("ProgramName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ContractId {
            get {
                return this.contractIdField;
            }
            set {
                this.contractIdField = value;
                this.RaisePropertyChanged("ContractId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ContractNumber {
            get {
                return this.contractNumberField;
            }
            set {
                this.contractNumberField = value;
                this.RaisePropertyChanged("ContractNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ContractName {
            get {
                return this.contractNameField;
            }
            set {
                this.contractNameField = value;
                this.RaisePropertyChanged("ContractName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string RecipeId {
            get {
                return this.recipeIdField;
            }
            set {
                this.recipeIdField = value;
                this.RaisePropertyChanged("RecipeId");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocumentHash))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecipeReestr))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecipeClient2Out))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecipeClient2))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecipeClient))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(MnnItem))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RecipeReserveInfo))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Recipe))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public abstract partial class Entity : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecipeResponseInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string idField;
        
        private string codeField;
        
        private string unifyIdField;
        
        private string contractorIdField;
        
        private string supplierIdField;
        
        private string idGosContractField;
        
        private string idGosContractGoodsField;
        
        private string idChequeItemGlobalField;
        
        private string idLotGlobalField;
        
        private decimal retailPriceField;
        
        private decimal quantityField;
        
        private System.DateTime saleDateField;
        
        private bool saleDateFieldSpecified;
        
        private System.DateTime chequeDateField;
        
        private bool chequeDateFieldSpecified;
        
        private int denominatorField;
        
        private string noteField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string UnifyId {
            get {
                return this.unifyIdField;
            }
            set {
                this.unifyIdField = value;
                this.RaisePropertyChanged("UnifyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContractorId {
            get {
                return this.contractorIdField;
            }
            set {
                this.contractorIdField = value;
                this.RaisePropertyChanged("ContractorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string SupplierId {
            get {
                return this.supplierIdField;
            }
            set {
                this.supplierIdField = value;
                this.RaisePropertyChanged("SupplierId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string IdGosContract {
            get {
                return this.idGosContractField;
            }
            set {
                this.idGosContractField = value;
                this.RaisePropertyChanged("IdGosContract");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string IdGosContractGoods {
            get {
                return this.idGosContractGoodsField;
            }
            set {
                this.idGosContractGoodsField = value;
                this.RaisePropertyChanged("IdGosContractGoods");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string IdChequeItemGlobal {
            get {
                return this.idChequeItemGlobalField;
            }
            set {
                this.idChequeItemGlobalField = value;
                this.RaisePropertyChanged("IdChequeItemGlobal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string IdLotGlobal {
            get {
                return this.idLotGlobalField;
            }
            set {
                this.idLotGlobalField = value;
                this.RaisePropertyChanged("IdLotGlobal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public decimal RetailPrice {
            get {
                return this.retailPriceField;
            }
            set {
                this.retailPriceField = value;
                this.RaisePropertyChanged("RetailPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public System.DateTime SaleDate {
            get {
                return this.saleDateField;
            }
            set {
                this.saleDateField = value;
                this.RaisePropertyChanged("SaleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleDateSpecified {
            get {
                return this.saleDateFieldSpecified;
            }
            set {
                this.saleDateFieldSpecified = value;
                this.RaisePropertyChanged("SaleDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public System.DateTime ChequeDate {
            get {
                return this.chequeDateField;
            }
            set {
                this.chequeDateField = value;
                this.RaisePropertyChanged("ChequeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ChequeDateSpecified {
            get {
                return this.chequeDateFieldSpecified;
            }
            set {
                this.chequeDateFieldSpecified = value;
                this.RaisePropertyChanged("ChequeDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public int Denominator {
            get {
                return this.denominatorField;
            }
            set {
                this.denominatorField = value;
                this.RaisePropertyChanged("Denominator");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class DocumentHash : Entity {
        
        private System.Guid documentIdField;
        
        private string documentTypeField;
        
        private System.Guid lgotaCrcField;
        
        private System.Guid efarmaCrcField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid DocumentId {
            get {
                return this.documentIdField;
            }
            set {
                this.documentIdField = value;
                this.RaisePropertyChanged("DocumentId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DocumentType {
            get {
                return this.documentTypeField;
            }
            set {
                this.documentTypeField = value;
                this.RaisePropertyChanged("DocumentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid LgotaCrc {
            get {
                return this.lgotaCrcField;
            }
            set {
                this.lgotaCrcField = value;
                this.RaisePropertyChanged("LgotaCrc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid EfarmaCrc {
            get {
                return this.efarmaCrcField;
            }
            set {
                this.efarmaCrcField = value;
                this.RaisePropertyChanged("EfarmaCrc");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecipeReestr : Entity {
        
        private System.Guid reestrGuidField;
        
        private bool reestrGuidFieldSpecified;
        
        private System.Guid reestrItemGuidField;
        
        private bool reestrItemGuidFieldSpecified;
        
        private System.Guid reestrItemDetailGuidField;
        
        private bool reestrItemDetailGuidFieldSpecified;
        
        private System.Guid idChequeItemGlobalField;
        
        private bool idChequeItemGlobalFieldSpecified;
        
        private System.DateTime reestrDateField;
        
        private bool reestrDateFieldSpecified;
        
        private string reestrNumberField;
        
        private string reestrStateField;
        
        private string reestrItemDetailStateField;
        
        private System.DateTime deletedField;
        
        private bool deletedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ReestrGuid {
            get {
                return this.reestrGuidField;
            }
            set {
                this.reestrGuidField = value;
                this.RaisePropertyChanged("ReestrGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReestrGuidSpecified {
            get {
                return this.reestrGuidFieldSpecified;
            }
            set {
                this.reestrGuidFieldSpecified = value;
                this.RaisePropertyChanged("ReestrGuidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ReestrItemGuid {
            get {
                return this.reestrItemGuidField;
            }
            set {
                this.reestrItemGuidField = value;
                this.RaisePropertyChanged("ReestrItemGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReestrItemGuidSpecified {
            get {
                return this.reestrItemGuidFieldSpecified;
            }
            set {
                this.reestrItemGuidFieldSpecified = value;
                this.RaisePropertyChanged("ReestrItemGuidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid ReestrItemDetailGuid {
            get {
                return this.reestrItemDetailGuidField;
            }
            set {
                this.reestrItemDetailGuidField = value;
                this.RaisePropertyChanged("ReestrItemDetailGuid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReestrItemDetailGuidSpecified {
            get {
                return this.reestrItemDetailGuidFieldSpecified;
            }
            set {
                this.reestrItemDetailGuidFieldSpecified = value;
                this.RaisePropertyChanged("ReestrItemDetailGuidSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.Guid IdChequeItemGlobal {
            get {
                return this.idChequeItemGlobalField;
            }
            set {
                this.idChequeItemGlobalField = value;
                this.RaisePropertyChanged("IdChequeItemGlobal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IdChequeItemGlobalSpecified {
            get {
                return this.idChequeItemGlobalFieldSpecified;
            }
            set {
                this.idChequeItemGlobalFieldSpecified = value;
                this.RaisePropertyChanged("IdChequeItemGlobalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime ReestrDate {
            get {
                return this.reestrDateField;
            }
            set {
                this.reestrDateField = value;
                this.RaisePropertyChanged("ReestrDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReestrDateSpecified {
            get {
                return this.reestrDateFieldSpecified;
            }
            set {
                this.reestrDateFieldSpecified = value;
                this.RaisePropertyChanged("ReestrDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ReestrNumber {
            get {
                return this.reestrNumberField;
            }
            set {
                this.reestrNumberField = value;
                this.RaisePropertyChanged("ReestrNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string ReestrState {
            get {
                return this.reestrStateField;
            }
            set {
                this.reestrStateField = value;
                this.RaisePropertyChanged("ReestrState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ReestrItemDetailState {
            get {
                return this.reestrItemDetailStateField;
            }
            set {
                this.reestrItemDetailStateField = value;
                this.RaisePropertyChanged("ReestrItemDetailState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public System.DateTime Deleted {
            get {
                return this.deletedField;
            }
            set {
                this.deletedField = value;
                this.RaisePropertyChanged("Deleted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DeletedSpecified {
            get {
                return this.deletedFieldSpecified;
            }
            set {
                this.deletedFieldSpecified = value;
                this.RaisePropertyChanged("DeletedSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecipeClient2Out : Entity {
        
        private string idField;
        
        private string seriaField;
        
        private string numberField;
        
        private string errorCodeField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Seria {
            get {
                return this.seriaField;
            }
            set {
                this.seriaField = value;
                this.RaisePropertyChanged("Seria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecipeClient2 : Entity {
        
        private string programNameField;
        
        private string seriaField;
        
        private string numberField;
        
        private string doctorCodeField;
        
        private string lpuOgrnField;
        
        private string lpuFomsField;
        
        private string snilsField;
        
        private string patientLastnameField;
        
        private string patientFirstnameField;
        
        private string patientMiddlenameField;
        
        private System.DateTime patientBirthdayField;
        
        private string patientSexField;
        
        private string documnentStateField;
        
        private string privilegeCodeField;
        
        private int fundingSourceCodeField;
        
        private string nosologyCodeField;
        
        private string mkbCodeField;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private bool isVkField;
        
        private string validPeriodCodeField;
        
        private int payPercentField;
        
        private string mnnCodeField;
        
        private string trnCodeField;
        
        private string productCodeField;
        
        private string dosageField;
        
        private string cureformCodeField;
        
        private decimal quantityField;
        
        private int quantityUnitField;
        
        private System.DateTime saleDateField;
        
        private bool saleDateFieldSpecified;
        
        private System.DateTime incomeDateField;
        
        private bool incomeDateFieldSpecified;
        
        private decimal priceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ProgramName {
            get {
                return this.programNameField;
            }
            set {
                this.programNameField = value;
                this.RaisePropertyChanged("ProgramName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Seria {
            get {
                return this.seriaField;
            }
            set {
                this.seriaField = value;
                this.RaisePropertyChanged("Seria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string DoctorCode {
            get {
                return this.doctorCodeField;
            }
            set {
                this.doctorCodeField = value;
                this.RaisePropertyChanged("DoctorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LpuOgrn {
            get {
                return this.lpuOgrnField;
            }
            set {
                this.lpuOgrnField = value;
                this.RaisePropertyChanged("LpuOgrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LpuFoms {
            get {
                return this.lpuFomsField;
            }
            set {
                this.lpuFomsField = value;
                this.RaisePropertyChanged("LpuFoms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Snils {
            get {
                return this.snilsField;
            }
            set {
                this.snilsField = value;
                this.RaisePropertyChanged("Snils");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string PatientLastname {
            get {
                return this.patientLastnameField;
            }
            set {
                this.patientLastnameField = value;
                this.RaisePropertyChanged("PatientLastname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string PatientFirstname {
            get {
                return this.patientFirstnameField;
            }
            set {
                this.patientFirstnameField = value;
                this.RaisePropertyChanged("PatientFirstname");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string PatientMiddlename {
            get {
                return this.patientMiddlenameField;
            }
            set {
                this.patientMiddlenameField = value;
                this.RaisePropertyChanged("PatientMiddlename");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public System.DateTime PatientBirthday {
            get {
                return this.patientBirthdayField;
            }
            set {
                this.patientBirthdayField = value;
                this.RaisePropertyChanged("PatientBirthday");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string PatientSex {
            get {
                return this.patientSexField;
            }
            set {
                this.patientSexField = value;
                this.RaisePropertyChanged("PatientSex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string DocumnentState {
            get {
                return this.documnentStateField;
            }
            set {
                this.documnentStateField = value;
                this.RaisePropertyChanged("DocumnentState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string PrivilegeCode {
            get {
                return this.privilegeCodeField;
            }
            set {
                this.privilegeCodeField = value;
                this.RaisePropertyChanged("PrivilegeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public int FundingSourceCode {
            get {
                return this.fundingSourceCodeField;
            }
            set {
                this.fundingSourceCodeField = value;
                this.RaisePropertyChanged("FundingSourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string NosologyCode {
            get {
                return this.nosologyCodeField;
            }
            set {
                this.nosologyCodeField = value;
                this.RaisePropertyChanged("NosologyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string MkbCode {
            get {
                return this.mkbCodeField;
            }
            set {
                this.mkbCodeField = value;
                this.RaisePropertyChanged("MkbCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
                this.RaisePropertyChanged("IssueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public bool IsVk {
            get {
                return this.isVkField;
            }
            set {
                this.isVkField = value;
                this.RaisePropertyChanged("IsVk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string ValidPeriodCode {
            get {
                return this.validPeriodCodeField;
            }
            set {
                this.validPeriodCodeField = value;
                this.RaisePropertyChanged("ValidPeriodCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int PayPercent {
            get {
                return this.payPercentField;
            }
            set {
                this.payPercentField = value;
                this.RaisePropertyChanged("PayPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string MnnCode {
            get {
                return this.mnnCodeField;
            }
            set {
                this.mnnCodeField = value;
                this.RaisePropertyChanged("MnnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string TrnCode {
            get {
                return this.trnCodeField;
            }
            set {
                this.trnCodeField = value;
                this.RaisePropertyChanged("TrnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string ProductCode {
            get {
                return this.productCodeField;
            }
            set {
                this.productCodeField = value;
                this.RaisePropertyChanged("ProductCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string Dosage {
            get {
                return this.dosageField;
            }
            set {
                this.dosageField = value;
                this.RaisePropertyChanged("Dosage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string CureformCode {
            get {
                return this.cureformCodeField;
            }
            set {
                this.cureformCodeField = value;
                this.RaisePropertyChanged("CureformCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public int QuantityUnit {
            get {
                return this.quantityUnitField;
            }
            set {
                this.quantityUnitField = value;
                this.RaisePropertyChanged("QuantityUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public System.DateTime SaleDate {
            get {
                return this.saleDateField;
            }
            set {
                this.saleDateField = value;
                this.RaisePropertyChanged("SaleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleDateSpecified {
            get {
                return this.saleDateFieldSpecified;
            }
            set {
                this.saleDateFieldSpecified = value;
                this.RaisePropertyChanged("SaleDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public System.DateTime IncomeDate {
            get {
                return this.incomeDateField;
            }
            set {
                this.incomeDateField = value;
                this.RaisePropertyChanged("IncomeDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncomeDateSpecified {
            get {
                return this.incomeDateFieldSpecified;
            }
            set {
                this.incomeDateFieldSpecified = value;
                this.RaisePropertyChanged("IncomeDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public decimal Price {
            get {
                return this.priceField;
            }
            set {
                this.priceField = value;
                this.RaisePropertyChanged("Price");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RecipeClient : Entity {
        
        private string seriaField;
        
        private string numberField;
        
        private string snilsField;
        
        private bool patientFoundField;
        
        private string lpuOgrnField;
        
        private string lpuFomsField;
        
        private bool lpuFoundField;
        
        private string doctorCodeField;
        
        private bool doctorFoundField;
        
        private string mkbCodeField;
        
        private bool mkbFoundField;
        
        private int fundingSourceCodeField;
        
        private bool fundingSourceFoundField;
        
        private string nosologyCodeField;
        
        private bool nosologyFoundField;
        
        private string privilegeCodeField;
        
        private bool privilegeCodeFoundField;
        
        private bool programFoundField;
        
        private string validPeriodCodeField;
        
        private bool validPeriodFoundField;
        
        private int payPercentField;
        
        private bool payPercentFoundField;
        
        private bool isTrnField;
        
        private string trnCodeField;
        
        private bool trnFoundField;
        
        private string mnnCodeField;
        
        private bool mnnFoundField;
        
        private string cureformCodeField;
        
        private bool cureformFoundField;
        
        private string unitCodeField;
        
        private bool unitFoundField;
        
        private bool isVkField;
        
        private string dosageField;
        
        private decimal quantityField;
        
        private System.DateTime saleDateField;
        
        private bool saleDateFieldSpecified;
        
        private System.DateTime issueDateField;
        
        private bool issueDateFieldSpecified;
        
        private System.DateTime expirationDateField;
        
        private bool expirationDateFieldSpecified;
        
        private string recipeCheckField;
        
        private bool uploadedField;
        
        private bool isAnnulledField;
        
        private string causeOfAnnulmentField;
        
        private bool causeOfAnnulmentFoundField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Seria {
            get {
                return this.seriaField;
            }
            set {
                this.seriaField = value;
                this.RaisePropertyChanged("Seria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Snils {
            get {
                return this.snilsField;
            }
            set {
                this.snilsField = value;
                this.RaisePropertyChanged("Snils");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool PatientFound {
            get {
                return this.patientFoundField;
            }
            set {
                this.patientFoundField = value;
                this.RaisePropertyChanged("PatientFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string LpuOgrn {
            get {
                return this.lpuOgrnField;
            }
            set {
                this.lpuOgrnField = value;
                this.RaisePropertyChanged("LpuOgrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string LpuFoms {
            get {
                return this.lpuFomsField;
            }
            set {
                this.lpuFomsField = value;
                this.RaisePropertyChanged("LpuFoms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public bool LpuFound {
            get {
                return this.lpuFoundField;
            }
            set {
                this.lpuFoundField = value;
                this.RaisePropertyChanged("LpuFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string DoctorCode {
            get {
                return this.doctorCodeField;
            }
            set {
                this.doctorCodeField = value;
                this.RaisePropertyChanged("DoctorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public bool DoctorFound {
            get {
                return this.doctorFoundField;
            }
            set {
                this.doctorFoundField = value;
                this.RaisePropertyChanged("DoctorFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string MkbCode {
            get {
                return this.mkbCodeField;
            }
            set {
                this.mkbCodeField = value;
                this.RaisePropertyChanged("MkbCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public bool MkbFound {
            get {
                return this.mkbFoundField;
            }
            set {
                this.mkbFoundField = value;
                this.RaisePropertyChanged("MkbFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public int FundingSourceCode {
            get {
                return this.fundingSourceCodeField;
            }
            set {
                this.fundingSourceCodeField = value;
                this.RaisePropertyChanged("FundingSourceCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public bool FundingSourceFound {
            get {
                return this.fundingSourceFoundField;
            }
            set {
                this.fundingSourceFoundField = value;
                this.RaisePropertyChanged("FundingSourceFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string NosologyCode {
            get {
                return this.nosologyCodeField;
            }
            set {
                this.nosologyCodeField = value;
                this.RaisePropertyChanged("NosologyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public bool NosologyFound {
            get {
                return this.nosologyFoundField;
            }
            set {
                this.nosologyFoundField = value;
                this.RaisePropertyChanged("NosologyFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string PrivilegeCode {
            get {
                return this.privilegeCodeField;
            }
            set {
                this.privilegeCodeField = value;
                this.RaisePropertyChanged("PrivilegeCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public bool PrivilegeCodeFound {
            get {
                return this.privilegeCodeFoundField;
            }
            set {
                this.privilegeCodeFoundField = value;
                this.RaisePropertyChanged("PrivilegeCodeFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public bool ProgramFound {
            get {
                return this.programFoundField;
            }
            set {
                this.programFoundField = value;
                this.RaisePropertyChanged("ProgramFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string ValidPeriodCode {
            get {
                return this.validPeriodCodeField;
            }
            set {
                this.validPeriodCodeField = value;
                this.RaisePropertyChanged("ValidPeriodCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public bool ValidPeriodFound {
            get {
                return this.validPeriodFoundField;
            }
            set {
                this.validPeriodFoundField = value;
                this.RaisePropertyChanged("ValidPeriodFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public int PayPercent {
            get {
                return this.payPercentField;
            }
            set {
                this.payPercentField = value;
                this.RaisePropertyChanged("PayPercent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public bool PayPercentFound {
            get {
                return this.payPercentFoundField;
            }
            set {
                this.payPercentFoundField = value;
                this.RaisePropertyChanged("PayPercentFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public bool IsTrn {
            get {
                return this.isTrnField;
            }
            set {
                this.isTrnField = value;
                this.RaisePropertyChanged("IsTrn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string TrnCode {
            get {
                return this.trnCodeField;
            }
            set {
                this.trnCodeField = value;
                this.RaisePropertyChanged("TrnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public bool TrnFound {
            get {
                return this.trnFoundField;
            }
            set {
                this.trnFoundField = value;
                this.RaisePropertyChanged("TrnFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string MnnCode {
            get {
                return this.mnnCodeField;
            }
            set {
                this.mnnCodeField = value;
                this.RaisePropertyChanged("MnnCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public bool MnnFound {
            get {
                return this.mnnFoundField;
            }
            set {
                this.mnnFoundField = value;
                this.RaisePropertyChanged("MnnFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string CureformCode {
            get {
                return this.cureformCodeField;
            }
            set {
                this.cureformCodeField = value;
                this.RaisePropertyChanged("CureformCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public bool CureformFound {
            get {
                return this.cureformFoundField;
            }
            set {
                this.cureformFoundField = value;
                this.RaisePropertyChanged("CureformFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string UnitCode {
            get {
                return this.unitCodeField;
            }
            set {
                this.unitCodeField = value;
                this.RaisePropertyChanged("UnitCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public bool UnitFound {
            get {
                return this.unitFoundField;
            }
            set {
                this.unitFoundField = value;
                this.RaisePropertyChanged("UnitFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public bool IsVk {
            get {
                return this.isVkField;
            }
            set {
                this.isVkField = value;
                this.RaisePropertyChanged("IsVk");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string Dosage {
            get {
                return this.dosageField;
            }
            set {
                this.dosageField = value;
                this.RaisePropertyChanged("Dosage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public decimal Quantity {
            get {
                return this.quantityField;
            }
            set {
                this.quantityField = value;
                this.RaisePropertyChanged("Quantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public System.DateTime SaleDate {
            get {
                return this.saleDateField;
            }
            set {
                this.saleDateField = value;
                this.RaisePropertyChanged("SaleDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SaleDateSpecified {
            get {
                return this.saleDateFieldSpecified;
            }
            set {
                this.saleDateFieldSpecified = value;
                this.RaisePropertyChanged("SaleDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public System.DateTime IssueDate {
            get {
                return this.issueDateField;
            }
            set {
                this.issueDateField = value;
                this.RaisePropertyChanged("IssueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssueDateSpecified {
            get {
                return this.issueDateFieldSpecified;
            }
            set {
                this.issueDateFieldSpecified = value;
                this.RaisePropertyChanged("IssueDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public System.DateTime ExpirationDate {
            get {
                return this.expirationDateField;
            }
            set {
                this.expirationDateField = value;
                this.RaisePropertyChanged("ExpirationDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ExpirationDateSpecified {
            get {
                return this.expirationDateFieldSpecified;
            }
            set {
                this.expirationDateFieldSpecified = value;
                this.RaisePropertyChanged("ExpirationDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string RecipeCheck {
            get {
                return this.recipeCheckField;
            }
            set {
                this.recipeCheckField = value;
                this.RaisePropertyChanged("RecipeCheck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public bool Uploaded {
            get {
                return this.uploadedField;
            }
            set {
                this.uploadedField = value;
                this.RaisePropertyChanged("Uploaded");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public bool IsAnnulled {
            get {
                return this.isAnnulledField;
            }
            set {
                this.isAnnulledField = value;
                this.RaisePropertyChanged("IsAnnulled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string CauseOfAnnulment {
            get {
                return this.causeOfAnnulmentField;
            }
            set {
                this.causeOfAnnulmentField = value;
                this.RaisePropertyChanged("CauseOfAnnulment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public bool CauseOfAnnulmentFound {
            get {
                return this.causeOfAnnulmentFoundField;
            }
            set {
                this.causeOfAnnulmentFoundField = value;
                this.RaisePropertyChanged("CauseOfAnnulmentFound");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MnnItem : Entity {
        
        private string seriaField;
        
        private string numberField;
        
        private string idField;
        
        private string mnnIdField;
        
        private string mnnNameField;
        
        private string codeField;
        
        private string nameField;
        
        private string nameLatField;
        
        private string noteField;
        
        private string recipeIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Seria {
            get {
                return this.seriaField;
            }
            set {
                this.seriaField = value;
                this.RaisePropertyChanged("Seria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Number {
            get {
                return this.numberField;
            }
            set {
                this.numberField = value;
                this.RaisePropertyChanged("Number");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string MnnId {
            get {
                return this.mnnIdField;
            }
            set {
                this.mnnIdField = value;
                this.RaisePropertyChanged("MnnId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string MnnName {
            get {
                return this.mnnNameField;
            }
            set {
                this.mnnNameField = value;
                this.RaisePropertyChanged("MnnName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string NameLat {
            get {
                return this.nameLatField;
            }
            set {
                this.nameLatField = value;
                this.RaisePropertyChanged("NameLat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string RecipeId {
            get {
                return this.recipeIdField;
            }
            set {
                this.recipeIdField = value;
                this.RaisePropertyChanged("RecipeId");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RecipeServiceSoapChannel : Escyug.Converter.Models.RecipesServiceReference.RecipeServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RecipeServiceSoapClient : System.ServiceModel.ClientBase<Escyug.Converter.Models.RecipesServiceReference.RecipeServiceSoap>, Escyug.Converter.Models.RecipesServiceReference.RecipeServiceSoap {
        
        public RecipeServiceSoapClient() {
        }
        
        public RecipeServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RecipeServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RecipeServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.Recipe[] RecipeRequest(string clientId) {
            return base.Channel.RecipeRequest(clientId);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.Recipe[]> RecipeRequestAsync(string clientId) {
            return base.Channel.RecipeRequestAsync(clientId);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.Recipe[] RecipeRequestRepeat(string clientId) {
            return base.Channel.RecipeRequestRepeat(clientId);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.Recipe[]> RecipeRequestRepeatAsync(string clientId) {
            return base.Channel.RecipeRequestRepeatAsync(clientId);
        }
        
        public void RecipeResponse(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo[] recipes) {
            base.Channel.RecipeResponse(clientId, recipes);
        }
        
        public System.Threading.Tasks.Task RecipeResponseAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo[] recipes) {
            return base.Channel.RecipeResponseAsync(clientId, recipes);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.Recipe RecipeFind(string clientId, string seria, string number, System.DateTime saleDate) {
            return base.Channel.RecipeFind(clientId, seria, number, saleDate);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.Recipe> RecipeFindAsync(string clientId, string seria, string number, System.DateTime saleDate) {
            return base.Channel.RecipeFindAsync(clientId, seria, number, saleDate);
        }
        
        public string RecipeCheck(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo) {
            return base.Channel.RecipeCheck(clientId, recipeInfo);
        }
        
        public System.Threading.Tasks.Task<string> RecipeCheckAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo) {
            return base.Channel.RecipeCheckAsync(clientId, recipeInfo);
        }
        
        public string RecipeEditCheck(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo) {
            return base.Channel.RecipeEditCheck(clientId, recipeInfo);
        }
        
        public System.Threading.Tasks.Task<string> RecipeEditCheckAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeResponseInfo recipeInfo) {
            return base.Channel.RecipeEditCheckAsync(clientId, recipeInfo);
        }
        
        public string RecipeDelay(string clientId, string seria, string number, System.DateTime incomeDate) {
            return base.Channel.RecipeDelay(clientId, seria, number, incomeDate);
        }
        
        public System.Threading.Tasks.Task<string> RecipeDelayAsync(string clientId, string seria, string number, System.DateTime incomeDate) {
            return base.Channel.RecipeDelayAsync(clientId, seria, number, incomeDate);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.RecipeClient RecipeClientSave(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient recipe) {
            return base.Channel.RecipeClientSave(clientId, recipe);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeClient> RecipeClientSaveAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient recipe) {
            return base.Channel.RecipeClientSaveAsync(clientId, recipe);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.RecipeClient[] RecipesClientSave(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient[] recipes) {
            return base.Channel.RecipesClientSave(clientId, recipes);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeClient[]> RecipesClientSaveAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient[] recipes) {
            return base.Channel.RecipesClientSaveAsync(clientId, recipes);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.RecipeClient2Out[] RecipesClient2Save(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient2[] recipes) {
            return base.Channel.RecipesClient2Save(clientId, recipes);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeClient2Out[]> RecipesClient2SaveAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.RecipeClient2[] recipes) {
            return base.Channel.RecipesClient2SaveAsync(clientId, recipes);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.RecipeReestr[] RecipeReestrRequest(string clientId) {
            return base.Channel.RecipeReestrRequest(clientId);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.RecipeReestr[]> RecipeReestrRequestAsync(string clientId) {
            return base.Channel.RecipeReestrRequestAsync(clientId);
        }
        
        public Escyug.Converter.Models.RecipesServiceReference.DocumentHash[] RecipesClientHashesExchange(string clientId, Escyug.Converter.Models.RecipesServiceReference.DocumentHash[] documentHashes) {
            return base.Channel.RecipesClientHashesExchange(clientId, documentHashes);
        }
        
        public System.Threading.Tasks.Task<Escyug.Converter.Models.RecipesServiceReference.DocumentHash[]> RecipesClientHashesExchangeAsync(string clientId, Escyug.Converter.Models.RecipesServiceReference.DocumentHash[] documentHashes) {
            return base.Channel.RecipesClientHashesExchangeAsync(clientId, documentHashes);
        }
    }
}
